import { PageIntro } from "./components/ui";

const sections = [
  {
    number: "01",
    title: "About Trichofy",
    body: [
      `Trichofy is a South African BeautyTech company providing AI-powered hair and scalp analysis. By accessing or using the Trichofy website, app, or services (the "Services"), you agree to these Terms & Conditions. If you do not agree, please do not use the Services.`,
      `These Terms apply to all visitors, registered users, salon partners, and anyone who uploads an image for analysis. We may update these Terms from time to time, and continued use of the Services means you accept the current version.`,
    ],
  },
  {
    number: "02",
    title: "Wellness Disclaimer",
    body: [
      `Trichofy provides cosmetic, grooming, and general wellness guidance only. Our analysis and recommendations are informational and are not a medical diagnosis, treatment, or professional medical advice.`,
      `Trichofy does not diagnose, treat, cure, or prevent any disease or medical condition (including hair loss, infections, or dermatological conditions). If you have a scalp or health concern, consult a qualified medical practitioner or dermatologist. Never disregard professional medical advice because of something provided by Trichofy.`,
    ],
  },
  {
    number: "03",
    title: "AI Analysis",
    body: [
      `Our hair and scalp insights are generated by machine-learning models that estimate characteristics such as hair type, density, texture, and scalp condition from the images and information you provide.`,
      `AI results are probabilistic estimates and may be inaccurate or incomplete. Accuracy can vary with image quality, lighting, and angle. You should treat all outputs as guidance, not as definitive fact, and use your own judgement.`,
    ],
  },
  {
    number: "04",
    title: "Image Uploads",
    body: [
      `To use certain features you may upload photographs of your hair and scalp. By uploading, you confirm that:`,
    ],
    list: [
      "You are the person in the image, or have their permission to upload it.",
      "You are 18 or older, or have guardian consent.",
      "You will not upload unlawful, offensive, or infringing content.",
    ],
    after: [
      `You retain ownership of your images. You grant Trichofy a limited licence to process them solely to deliver the Services described in these Terms.`,
    ],
  },
  {
    number: "05",
    title: "POPIA & Privacy",
    body: [
      `Trichofy processes personal information in line with the Protection of Personal Information Act, 2013 (POPIA). Photographs and related data are treated as sensitive and handled with appropriate safeguards.`,
      `We collect only what we need to provide analysis, store data securely, and we do not sell your personal information. You have the right to access, correct, or request deletion of your data, and to object to processing.`,
      `For full details, see our Privacy Policy. To exercise your rights, contact our Information Officer (see Contact).`,
    ],
  },
  {
    number: "06",
    title: "AI Model Improvement",
    body: [
      `With your consent, Trichofy may use de-identified images and analysis data to train and improve our AI models and Services. Where used for model improvement, data is stripped of direct identifiers wherever practicable.`,
      `You may opt out of model-improvement use at any time in your settings or by contacting us, without losing access to core analysis features.`,
    ],
  },
  {
    number: "07",
    title: "Salons & Partners",
    body: [
      `Trichofy may connect you with independent salons, stylists, trichologists, and brand partners. These partners are independent third parties and are not employed or controlled by Trichofy.`,
      `Any booking, consultation, treatment, or transaction you enter into with a partner is solely between you and that partner. Trichofy is not responsible for the services, conduct, pricing, or outcomes provided by third-party partners.`,
    ],
  },
  {
    number: "08",
    title: "Product Recommendations",
    body: [
      `Trichofy may suggest hair-care products and routines based on your analysis. Recommendations are suggestions only and may include partner or affiliate products from which we may earn a commission.`,
      `Always read product labels and patch-test new products. Discontinue use and seek advice if you experience irritation or an adverse reaction. Trichofy is not liable for reactions to third-party products.`,
    ],
  },
  {
    number: "09",
    title: "User Rules",
    body: [`When using Trichofy you agree not to:`],
    list: [
      "Misuse, disrupt, or attempt to gain unauthorised access to the Services.",
      "Upload unlawful, harmful, or infringing content.",
      "Reverse engineer, scrape, or copy our models or content.",
      "Impersonate others or use the Services for any unlawful purpose.",
    ],
    after: [`We may suspend or terminate access for any breach of these Terms.`],
  },
  {
    number: "10",
    title: "Liability",
    body: [
      `To the maximum extent permitted by law, Trichofy provides the Services "as is" and "as available" without warranties of any kind. We are not liable for any indirect, incidental, or consequential loss, or for decisions made in reliance on AI outputs, third-party partners, or product recommendations.`,
      `Nothing in these Terms excludes liability that cannot be excluded under South African law, including under the Consumer Protection Act where it applies.`,
    ],
  },
  {
    number: "11",
    title: "Governing Law",
    body: [
      `These Terms are governed by the laws of the Republic of South Africa, and any dispute is subject to the exclusive jurisdiction of the South African courts. If any provision is found unenforceable, the remaining provisions continue in full force.`,
    ],
  },
];

export function TermsPage() {
  return (
    <div className="page terms-page">
      <section className="terms-hero section-pad">
        <PageIntro
          eyebrow="Trichofy · Legal"
          title="Terms & Conditions"
          text="Clear, privacy-first terms for AI-powered hair and scalp insights."
        />
        <p className="terms-updated">Last updated · 28 June 2026</p>

        <div className="terms-callout">
          <span className="terms-callout-icon">!</span>
          <div>
            <strong>Important wellness disclaimer</strong>
            <p>Trichofy provides cosmetic and wellness guidance only. It does not diagnose disease or replace medical advice.</p>
          </div>
        </div>
      </section>

      <section className="terms-body section-pad">
        {sections.map((section) => (
          <article key={section.number} className="terms-section">
            <h2><span className="terms-number">{section.number}</span> {section.title}</h2>
            {section.body.map((para, i) => <p key={i}>{para}</p>)}
            {section.list && (
              <ul>
                {section.list.map((item, i) => <li key={i}>{item}</li>)}
              </ul>
            )}
            {section.after?.map((para, i) => <p key={`after-${i}`}>{para}</p>)}
          </article>
        ))}

        <article className="terms-section terms-contact">
          <h2><span className="terms-number">12</span> Contact</h2>
          <p>Questions about these Terms or your data? We're here to help.</p>
          <div className="terms-contact-grid">
            <div>
              <p className="terms-contact-label">General</p>
              <a href="mailto:hello@trichofy.co.za">hello@trichofy.co.za</a>
            </div>
            <div>
              <p className="terms-contact-label">Information Officer</p>
              <a href="mailto:privacy@trichofy.co.za">privacy@trichofy.co.za</a>
            </div>
            <div>
              <p className="terms-contact-label">Web</p>
              <a href="https://trichofy.co.za">trichofy.co.za</a>
            </div>
          </div>
        </article>
      </section>
    </div>
  );
}
